### ISSUE TITLE
 Support localization

### ISSUE THREAD

**Issue by p-bo** [bcecchinato/user_unix_script#1]
Hello,
Would it be possible to follow instructions on:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#adding-translations
...and make your app more accessible for non-English speakers please?

Thanks :-)

**Comment by bcecchinato** [comment]
@p-bo This app has no UI so I can't tell which translation is missing ?

**Comment by p-bo** [comment]
@bcecchinato You are right - this app has only backend and in it, there is only one string. Until localized info.xml from appinfo will be used in app store, is this pointless. Sorry for noise :-)
